site_name: Iso-St3ph DevOps Portfolio
site_url: https://devops.ayoskip.info/
repo_url: https://github.com/iso-st3ph/homelab-devops
repo_name: iso-st3ph/homelab-devops

theme:
  name: material
  features:
    - navigation.instant
    - navigation.footer
    - navigation.tracking
    - toc.integrate
    - content.code.copy
    - content.action.edit
    - search.suggest
    - search.highlight
    - tabs
    - diagrams
  palette:
    - scheme: slate
      primary: indigo
      accent: cyan
  icon:
    repo: fontawesome/brands/github

extra_javascript:
  - https://unpkg.com/mermaid@10/dist/mermaid.min.js
  - assets/mermaid-init.js

plugins:
  - search

markdown_extensions:
  - admonition
  - footnotes
  - toc:
      permalink: true
  - pymdownx.highlight
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.details
  - pymdownx.tabbed
  - pymdownx.tasklist
  - pymdownx.magiclink
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

nav:
  - Home: index.md
  - Architecture: architecture.md
  - Terraform: terraform.md
  - Ansible: ansible.md
  - Kubernetes (K3s): kubernetes.md
  - GitOps (ArgoCD): gitops.md
  - Jenkins CI/CD: jenkins.md
  - Packer Images: packer.md
  - Docker / Reverse Proxy: docker.md
  - Monitoring: monitoring.md
  - Grafana Dashboards: grafana-dashboards.md
  - Security Scanning: security.md
  - Hire Me: hire-me.md
