---
galaxy_info:
  author: iso-st3ph
  description: Install and configure Prometheus Node Exporter
  company: Homelab
  license: MIT
  min_ansible_version: "2.9"
  platforms:
    - name: Fedora
      versions:
        - all
    - name: EL
      versions:
        - 8
        - 9
    - name: Ubuntu
      versions:
        - focal
        - jammy
  galaxy_tags:
    - monitoring
    - prometheus
    - observability
    - metrics

dependencies: []
